//go:build linux && taintnative

package kernelfabric

import (
	"context"
	"crypto/ed25519"
	"crypto/rand"
	_ "embed"
	"errors"
	"fmt"
	"net"
	"os"
	"os/exec"
	"path/filepath"
	"syscall"
	"testing"
	"time"

	"golang.org/x/sys/unix"
)

// Generated by .github/workflows/taint-native-falsification.yml before the
// taintnative test binary is built. Keeping the filesystem image inside the test
// binary makes the inode-allocation schedule available in the fallback VM too.
//
//go:embed testdata/aegis_inode_reuse.ext4
var nativeInodeReuseExt4Image []byte

const taintInodeReuseHelperEnv = "AEGIS_TAINT_INODE_REUSE_HELPER"

func TestTaintInodeReuseHelper(t *testing.T) {
	if os.Getenv(taintInodeReuseHelperEnv) != "1" {
		return
	}

	var trigger [1]byte
	if _, err := os.Stdin.Read(trigger[:]); err != nil {
		t.Fatalf("wait for inode-reuse trigger: %v", err)
	}
	if err := expectNativeDialDenied(os.Getenv(taintNativeHelperAddr)); err != nil {
		t.Fatal(err)
	}
}

// TestNativeTaintSameInodeReuseFailsClosed directly forces allocator-level
// same-(device,inode) reuse after an enrolled source is unlinked. The new object
// must not recover effect authority merely because its numeric identity aliases
// the retired object. The proof deliberately keeps the child clean and does not
// let it read the replacement: denial must come from sticky source-continuity
// DIRTY, not from process taint.
func TestNativeTaintSameInodeReuseFailsClosed(t *testing.T) {
	if os.Geteuid() != 0 {
		t.Skip("native taint inode-reuse test requires root")
	}
	if len(nativeTaintBPFObject) == 0 {
		t.Fatal("embedded native taint BPF object is empty")
	}
	if len(nativeInodeReuseExt4Image) == 0 {
		t.Fatal("embedded inode-reuse ext4 image is empty")
	}
	if err := prepareNativeTaintKernel(); err != nil {
		t.Fatalf("prepare native taint kernel environment: %v", err)
	}

	originalCgroup, err := currentUnifiedCgroupPath()
	if err != nil {
		t.Fatal(err)
	}
	testID := fmt.Sprintf("aegis-taint-inode-reuse-%d", os.Getpid())
	cgroupPath := filepath.Join("/sys/fs/cgroup", testID)
	if err := os.Mkdir(cgroupPath, 0o755); err != nil {
		t.Fatalf("create inode-reuse cgroup: %v", err)
	}
	defer func() {
		_ = movePIDToCgroup(originalCgroup, os.Getpid())
		_ = os.Remove(cgroupPath)
	}()

	bpffsRoot := filepath.Join("/sys/fs/bpf", testID)
	if err := os.MkdirAll(bpffsRoot, 0o755); err != nil {
		t.Fatalf("create inode-reuse bpffs root: %v", err)
	}
	defer removeNativeTaintPins(bpffsRoot)

	artifact := filepath.Join(t.TempDir(), "aegis_taint.bpf.o")
	if err := os.WriteFile(artifact, nativeTaintBPFObject, 0o600); err != nil {
		t.Fatalf("materialize taint BPF object: %v", err)
	}

	fsImage := filepath.Join(t.TempDir(), "inode-reuse.ext4")
	if err := os.WriteFile(fsImage, nativeInodeReuseExt4Image, 0o600); err != nil {
		t.Fatalf("materialize inode-reuse ext4 image: %v", err)
	}
	loopPath, releaseLoop := attachNativeLoopDevice(t, fsImage)
	defer releaseLoop()

	mountPoint := filepath.Join(t.TempDir(), "inode-reuse-fs")
	if err := os.Mkdir(mountPoint, 0o700); err != nil {
		t.Fatalf("create inode-reuse mountpoint: %v", err)
	}
	if err := unix.Mount(loopPath, mountPoint, "ext4", unix.MS_NODEV|unix.MS_NOSUID, ""); err != nil {
		t.Fatalf("mount inode-reuse ext4 fixture: %v", err)
	}
	defer func() {
		if err := unix.Unmount(mountPoint, unix.MNT_DETACH); err != nil {
			t.Logf("unmount inode-reuse fixture: %v", err)
		}
	}()

	sourcePath := filepath.Join(mountPoint, "source.txt")
	if err := os.WriteFile(sourcePath, []byte("classified-source"), 0o600); err != nil {
		t.Fatalf("write inode-reuse source: %v", err)
	}
	enrolledUserKey, err := ResolveTaintFileKey(sourcePath)
	if err != nil {
		t.Fatalf("resolve enrolled source identity: %v", err)
	}

	// Exhaust every other allocatable inode while the enrolled source remains
	// alive. After unlinking source.txt, that retired inode is therefore the only
	// inode the next regular file can receive.
	saturated := false
	for i := 0; i < 4096; i++ {
		path := filepath.Join(mountPoint, fmt.Sprintf("filler-%04d", i))
		f, createErr := os.OpenFile(path, os.O_CREATE|os.O_EXCL|os.O_WRONLY, 0o600)
		if createErr != nil {
			if errors.Is(createErr, syscall.ENOSPC) {
				saturated = true
				break
			}
			t.Fatalf("fill inode table at %s: %v", path, createErr)
		}
		if closeErr := f.Close(); closeErr != nil {
			t.Fatalf("close inode filler %s: %v", path, closeErr)
		}
	}
	if !saturated {
		t.Fatal("inode-reuse fixture did not reach inode exhaustion")
	}

	now := time.Now().UTC()
	manifest, err := BuildTaintBootstrapManifest(
		artifact,
		now.Add(-time.Minute),
		now.Add(15*time.Minute),
	)
	if err != nil {
		t.Fatal(err)
	}
	releasePublic, releasePrivate, err := ed25519.GenerateKey(rand.Reader)
	if err != nil {
		t.Fatal(err)
	}
	signedManifest, err := SignBootstrapManifest(manifest, releasePrivate)
	if err != nil {
		t.Fatal(err)
	}
	releaseKeyID, err := BootstrapKeyID(releasePublic)
	if err != nil {
		t.Fatal(err)
	}
	_, attestationPrivate, err := ed25519.GenerateKey(rand.Reader)
	if err != nil {
		t.Fatal(err)
	}
	attestationPublic := attestationPrivate.Public().(ed25519.PublicKey)

	loader := TaintBootstrapLoader{}
	loaded, err := loader.LoadAndAttach(context.Background(), TaintBootstrapLoadRequest{
		ArtifactPath:          artifact,
		CgroupPath:            cgroupPath,
		BPFFSRoot:             bpffsRoot,
		SignedManifest:        signedManifest,
		Trust:                 BootstrapTrustStore{releaseKeyID: releasePublic},
		AttestationPrivateKey: attestationPrivate,
		Now:                   now,
	})
	if err != nil {
		t.Fatalf("load inode-reuse taint BPF programs: %v", err)
	}

	sourceKeys, err := ResolveTaintFileKeysObserved(bpffsRoot, sourcePath)
	if err != nil {
		t.Fatalf("kernel-observe inode-reuse source: %v", err)
	}
	if len(sourceKeys) == 0 {
		t.Fatal("inode-reuse source probe returned no kernel identities")
	}
	plan := TaintActivationPlan{
		CgroupPath:    cgroupPath,
		AllowedLabels: 0,
		Sources:       make([]TaintSourceBinding, 0, len(sourceKeys)),
	}
	for _, key := range sourceKeys {
		plan.Sources = append(plan.Sources, TaintSourceBinding{
			Path:   sourcePath,
			File:   key,
			Labels: 1,
		})
	}
	activated, err := ActivateTaintCgroup(TaintActivationRequest{
		BPFFSRoot:                     bpffsRoot,
		Plan:                          plan,
		SignedBootstrapReceipt:        loaded.SignedReceipt,
		BootstrapAttestationPublicKey: attestationPublic,
	})
	if err != nil {
		t.Fatalf("activate inode-reuse taint cgroup: %v", err)
	}

	dirtyBefore, err := TaintSourceIdentityDirtyState(bpffsRoot)
	if err != nil {
		t.Fatalf("read source continuity before inode reuse: %v", err)
	}
	if dirtyBefore != 0 {
		t.Fatalf("source continuity dirty before inode reuse: %d", dirtyBefore)
	}

	listener, err := net.Listen("tcp4", "127.0.0.1:0")
	if err != nil {
		t.Fatal(err)
	}
	defer listener.Close()
	go acceptNativeConnections(listener)

	if err := movePIDToCgroup(cgroupPath, os.Getpid()); err != nil {
		t.Fatalf("move inode-reuse test into protected cgroup: %v", err)
	}
	conn, err := net.DialTimeout("tcp4", listener.Addr().String(), time.Second)
	if err != nil {
		t.Fatalf("clean egress unexpectedly denied before inode reuse: %v", err)
	}
	_ = conn.Close()

	child := exec.Command(os.Args[0], "-test.run=^TestTaintInodeReuseHelper$")
	child.Env = append(os.Environ(),
		taintInodeReuseHelperEnv+"=1",
		taintNativeHelperAddr+"="+listener.Addr().String(),
	)
	childStdin, err := child.StdinPipe()
	if err != nil {
		t.Fatal(err)
	}
	child.Stdout = os.Stdout
	child.Stderr = os.Stderr
	if err := child.Start(); err != nil {
		t.Fatalf("start clean inode-reuse child: %v", err)
	}
	childPID := uint32(child.Process.Pid)

	if err := os.Remove(sourcePath); err != nil {
		t.Fatalf("unlink enrolled source: %v", err)
	}
	dirtyAfterUnlink, err := TaintSourceIdentityDirtyState(bpffsRoot)
	if err != nil {
		t.Fatalf("read source continuity after enrolled unlink: %v", err)
	}
	if dirtyAfterUnlink <= dirtyBefore {
		t.Fatalf(
			"enrolled unlink did not invalidate source continuity: before=%d after=%d key=%+v",
			dirtyBefore,
			dirtyAfterUnlink,
			enrolledUserKey,
		)
	}

	if err := os.WriteFile(sourcePath, []byte("future-reused-object"), 0o600); err != nil {
		t.Fatalf("create replacement after inode exhaustion: %v", err)
	}
	reusedKey, err := ResolveTaintFileKey(sourcePath)
	if err != nil {
		t.Fatalf("resolve reused source identity: %v", err)
	}
	if reusedKey != enrolledUserKey {
		t.Fatalf(
			"allocator did not reuse the retired inode: enrolled=%+v replacement=%+v",
			enrolledUserKey,
			reusedKey,
		)
	}

	matchedKernelIdentity := false
	for _, key := range sourceKeys {
		if key == reusedKey {
			matchedKernelIdentity = true
			break
		}
	}
	if !matchedKernelIdentity {
		t.Fatalf(
			"same-number reuse did not alias an enrolled kernel identity: enrolled_kernel=%+v replacement=%+v",
			sourceKeys,
			reusedKey,
		)
	}

	dirtyAfterReuse, err := TaintSourceIdentityDirtyState(bpffsRoot)
	if err != nil {
		t.Fatalf("read source continuity after same-number reuse: %v", err)
	}
	if dirtyAfterReuse < dirtyAfterUnlink {
		t.Fatalf(
			"source continuity regressed after inode reuse: unlink=%d reuse=%d",
			dirtyAfterUnlink,
			dirtyAfterReuse,
		)
	}

	// The child never reads sourcePath. Its process taint must remain clean; the
	// denied effect therefore demonstrates that same-number reuse cannot recover
	// authority once source continuity became unknown.
	if _, err := childStdin.Write([]byte("go")); err != nil {
		t.Fatal(err)
	}
	if err := childStdin.Close(); err != nil {
		t.Fatal(err)
	}
	if err := child.Wait(); err != nil {
		t.Fatalf("clean child escaped after same-number inode reuse: %v", err)
	}
	if err := assertNativeProcessUntainted(bpffsRoot, childPID); err != nil {
		t.Fatalf("inode-reuse denial was not isolated to source continuity: %v", err)
	}

	isActive, err := TaintCgroupActivationState(bpffsRoot, activated.CgroupID)
	if err != nil {
		t.Fatal(err)
	}
	if !isActive {
		t.Fatal("inode-reuse schedule removed protected-cgroup activation")
	}

	t.Logf(
		"same-number inode reuse failed closed: key=%+v dirty_before=%d dirty_after_unlink=%d dirty_after_reuse=%d",
		reusedKey,
		dirtyBefore,
		dirtyAfterUnlink,
		dirtyAfterReuse,
	)
}

func attachNativeLoopDevice(t *testing.T, imagePath string) (string, func()) {
	t.Helper()

	imageFD, err := unix.Open(imagePath, unix.O_RDWR|unix.O_CLOEXEC, 0)
	if err != nil {
		t.Fatalf("open inode-reuse image: %v", err)
	}

	const (
		loopSetFD = 0x4C00
		loopClrFD = 0x4C01
	)

	for i := 0; i < 32; i++ {
		loopPath := fmt.Sprintf("/dev/loop%d", i)
		if _, statErr := os.Stat(loopPath); errors.Is(statErr, os.ErrNotExist) {
			// Linux loop block devices use major 7. For minors below 256 the
			// encoded dev_t is simply (major << 8) | minor.
			if err := unix.Mknod(loopPath, unix.S_IFBLK|0o600, (7<<8)|i); err != nil && !errors.Is(err, syscall.EEXIST) {
				_ = unix.Close(imageFD)
				t.Fatalf("create %s: %v", loopPath, err)
			}
		}

		loopFD, openErr := unix.Open(loopPath, unix.O_RDWR|unix.O_CLOEXEC, 0)
		if openErr != nil {
			continue
		}
		_, _, errno := unix.Syscall(
			unix.SYS_IOCTL,
			uintptr(loopFD),
			uintptr(loopSetFD),
			uintptr(imageFD),
		)
		if errno == 0 {
			return loopPath, func() {
				_, _, _ = unix.Syscall(
					unix.SYS_IOCTL,
					uintptr(loopFD),
					uintptr(loopClrFD),
					0,
				)
				_ = unix.Close(loopFD)
				_ = unix.Close(imageFD)
			}
		}
		_ = unix.Close(loopFD)
		if errno != syscall.EBUSY {
			_ = unix.Close(imageFD)
			t.Fatalf("attach %s to inode-reuse image: %v", loopPath, errno)
		}
	}

	_ = unix.Close(imageFD)
	t.Fatal("no free loop device available for inode-reuse fixture")
	return "", func() {}
}
